apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: backend-ns
spec:
  accessModes:
    - ReadWriteOnce # for now we only had one node
  resources:
    requests:
      storage: 1Gi
